export const multivaultAbi = [
  { inputs: [], type: 'error', name: 'MultiVault_AdminOnly' },
  { inputs: [], type: 'error', name: 'MultiVault_AlreadyInitialized' },
  { inputs: [], type: 'error', name: 'MultiVault_ArraysNotSameLength' },
  { inputs: [], type: 'error', name: 'MultiVault_AtomDoesNotExist' },
  { inputs: [], type: 'error', name: 'MultiVault_BurnFromZeroAddress' },
  { inputs: [], type: 'error', name: 'MultiVault_BurnInsufficientBalance' },
  { inputs: [], type: 'error', name: 'MultiVault_DeployAccountFailed' },
  { inputs: [], type: 'error', name: 'MultiVault_DepositOrWithdrawZeroShares' },
  { inputs: [], type: 'error', name: 'MultiVault_HasCounterStake' },
  { inputs: [], type: 'error', name: 'MultiVault_InsufficientBalance' },
  {
    inputs: [],
    type: 'error',
    name: 'MultiVault_InsufficientDepositAmountToCoverFees',
  },
  {
    inputs: [],
    type: 'error',
    name: 'MultiVault_InsufficientRemainingSharesInVault',
  },
  { inputs: [], type: 'error', name: 'MultiVault_InvalidFeeSet' },
  { inputs: [], type: 'error', name: 'MultiVault_MinimumDeposit' },
  { inputs: [], type: 'error', name: 'MultiVault_NotAtomCreator' },
  { inputs: [], type: 'error', name: 'MultiVault_TransferFailed' },
  { inputs: [], type: 'error', name: 'MultiVault_VaultDoesNotExist' },
  { inputs: [], type: 'error', name: 'MultiVault_VaultIsTriple' },
  { inputs: [], type: 'error', name: 'MultiVault_VaultNotAtom' },
  { inputs: [], type: 'error', name: 'MultiVault_VaultNotTriple' },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'creator',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'address',
        name: 'atomWallet',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'bytes',
        name: 'atomData',
        type: 'bytes',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'vaultID',
        type: 'uint256',
        indexed: false,
      },
    ],
    type: 'event',
    name: 'AtomCreated',
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'sender',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'address',
        name: 'receiver',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'uint256',
        name: 'vaultBalance',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'assets',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'shares',
        type: 'uint256',
        indexed: false,
      },
      { internalType: 'uint256', name: 'id', type: 'uint256', indexed: false },
    ],
    type: 'event',
    name: 'Deposit',
    anonymous: false,
  },
  {
    inputs: [
      { internalType: 'uint8', name: 'version', type: 'uint8', indexed: false },
    ],
    type: 'event',
    name: 'Initialized',
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'creator',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'uint256',
        name: 'subjectId',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'predicateId',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'objectId',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'vaultID',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'tripleAtomVaultId',
        type: 'uint256',
        indexed: false,
      },
    ],
    type: 'event',
    name: 'TripleCreated',
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'sender',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'address',
        name: 'owner',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'uint256',
        name: 'vaultBalance',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'assets',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'shares',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'exitFee',
        type: 'uint256',
        indexed: false,
      },
      { internalType: 'uint256', name: 'id', type: 'uint256', indexed: false },
    ],
    type: 'event',
    name: 'Withdraw',
    anonymous: false,
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'assertTriple',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'atomConfig',
    outputs: [
      { internalType: 'uint256', name: 'atomCost', type: 'uint256' },
      { internalType: 'uint256', name: 'atomCreationFee', type: 'uint256' },
    ],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'atomEquityFeeAmount',
    outputs: [{ internalType: 'uint256', name: 'feeAmount', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
    name: 'atoms',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'bytes[]', name: 'atomData', type: 'bytes[]' }],
    stateMutability: 'payable',
    type: 'function',
    name: 'batchCreateAtom',
    outputs: [{ internalType: 'uint256[]', name: 'ids', type: 'uint256[]' }],
  },
  {
    inputs: [{ internalType: 'bytes[]', name: 'atomData', type: 'bytes[]' }],
    stateMutability: 'payable',
    type: 'function',
    name: 'batchCreateAtomCompressed',
    outputs: [{ internalType: 'uint256[]', name: 'ids', type: 'uint256[]' }],
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: 'subjectIds', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'predicateIds', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'objectIds', type: 'uint256[]' },
    ],
    stateMutability: 'payable',
    type: 'function',
    name: 'batchCreateTriple',
    outputs: [{ internalType: 'uint256[]', name: 'ids', type: 'uint256[]' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'computeAtomWalletAddr',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'convertToAssets',
    outputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'convertToShares',
    outputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'count',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'bytes', name: 'atomData', type: 'bytes' }],
    stateMutability: 'payable',
    type: 'function',
    name: 'createAtom',
    outputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'bytes', name: 'atomData', type: 'bytes' }],
    stateMutability: 'payable',
    type: 'function',
    name: 'createAtomCompressed',
    outputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'subjectId', type: 'uint256' },
      { internalType: 'uint256', name: 'predicateId', type: 'uint256' },
      { internalType: 'uint256', name: 'objectId', type: 'uint256' },
    ],
    stateMutability: 'payable',
    type: 'function',
    name: 'createTriple',
    outputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'currentSharePrice',
    outputs: [{ internalType: 'uint256', name: 'price', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'atomId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'deployAtomWallet',
    outputs: [{ internalType: 'address', name: 'atomWallet', type: 'address' }],
  },
  {
    inputs: [
      { internalType: 'address', name: 'receiver', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'payable',
    type: 'function',
    name: 'depositAtom',
    outputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'address', name: 'receiver', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'payable',
    type: 'function',
    name: 'depositTriple',
    outputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'entryFeeAmount',
    outputs: [{ internalType: 'uint256', name: 'feeAmount', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'exitFeeAmount',
    outputs: [{ internalType: 'uint256', name: 'feeAmount', type: 'uint256' }],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'generalConfig',
    outputs: [
      { internalType: 'address', name: 'admin', type: 'address' },
      { internalType: 'address', name: 'protocolVault', type: 'address' },
      { internalType: 'uint256', name: 'feeDenominator', type: 'uint256' },
      { internalType: 'uint256', name: 'minDeposit', type: 'uint256' },
      { internalType: 'uint256', name: 'minShare', type: 'uint256' },
    ],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'pure',
    type: 'function',
    name: 'getCounterIdFromTriple',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'getTripleAtoms',
    outputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'vaultId', type: 'uint256' },
      { internalType: 'address', name: 'user', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'getVaultBalance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'getVaultStates',
    outputs: [
      {
        internalType: 'struct Types.VaultState[]',
        name: 'states',
        type: 'tuple[]',
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'uint256', name: 'assets', type: 'uint256' },
          { internalType: 'uint256', name: 'shares', type: 'uint256' },
        ],
      },
    ],
  },
  {
    inputs: [
      {
        internalType: 'struct IEthMultiVault.GeneralConfig',
        name: '_generalConfig',
        type: 'tuple',
        components: [
          { internalType: 'address', name: 'admin', type: 'address' },
          { internalType: 'address', name: 'protocolVault', type: 'address' },
          { internalType: 'uint256', name: 'feeDenominator', type: 'uint256' },
          { internalType: 'uint256', name: 'minDeposit', type: 'uint256' },
          { internalType: 'uint256', name: 'minShare', type: 'uint256' },
        ],
      },
      {
        internalType: 'struct IEthMultiVault.AtomConfig',
        name: '_atomConfig',
        type: 'tuple',
        components: [
          { internalType: 'uint256', name: 'atomCost', type: 'uint256' },
          { internalType: 'uint256', name: 'atomCreationFee', type: 'uint256' },
        ],
      },
      {
        internalType: 'struct IEthMultiVault.TripleConfig',
        name: '_tripleConfig',
        type: 'tuple',
        components: [
          {
            internalType: 'uint256',
            name: 'tripleCreationFee',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'atomEquityFeeForTriple',
            type: 'uint256',
          },
        ],
      },
      {
        internalType: 'struct IEthMultiVault.WalletConfig',
        name: '_walletConfig',
        type: 'tuple',
        components: [
          {
            internalType: 'contract IPermit2',
            name: 'permit2',
            type: 'address',
          },
          { internalType: 'address', name: 'entryPoint', type: 'address' },
          { internalType: 'address', name: 'atomWarden', type: 'address' },
        ],
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'init',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'isTriple',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
  },
  {
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'maxRedeem',
    outputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'previewDeposit',
    outputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'previewRedeem',
    outputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'exitFees', type: 'uint256' },
    ],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'protocolFeeAmount',
    outputs: [{ internalType: 'uint256', name: 'feeAmount', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'address', name: 'receiver', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'redeemAtom',
    outputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'address', name: 'receiver', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'redeemTriple',
    outputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'address', name: '_admin', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setAdmin',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_atomCost', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setAtomCost',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_atomCreationFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setAtomCreationFee',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_atomEquityFeeForTriple',
        type: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setAtomEquityFee',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_id', type: 'uint256' },
      { internalType: 'uint256', name: '_entryFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setEntryFee',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_id', type: 'uint256' },
      { internalType: 'uint256', name: '_exitFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setExitFee',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_feeDenominator', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setFeeDenominator',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_minDeposit', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setMinDeposit',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_minShare', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setMinShare',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_id', type: 'uint256' },
      { internalType: 'uint256', name: '_protocolFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setProtocolFee',
  },
  {
    inputs: [
      { internalType: 'address', name: '_protocolVault', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setProtocolVault',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_tripleCreationFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setTripleCreationFee',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'address', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'tripleAtomShares',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'tripleConfig',
    outputs: [
      { internalType: 'uint256', name: 'tripleCreationFee', type: 'uint256' },
      {
        internalType: 'uint256',
        name: 'atomEquityFeeForTriple',
        type: 'uint256',
      },
    ],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'tripleHash',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'subjectId', type: 'uint256' },
      { internalType: 'uint256', name: 'predicateId', type: 'uint256' },
      { internalType: 'uint256', name: 'objectId', type: 'uint256' },
    ],
    stateMutability: 'pure',
    type: 'function',
    name: 'tripleHashFromAtoms',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'triples',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'vaultFees',
    outputs: [
      { internalType: 'uint256', name: 'entryFee', type: 'uint256' },
      { internalType: 'uint256', name: 'exitFee', type: 'uint256' },
      { internalType: 'uint256', name: 'protocolFee', type: 'uint256' },
    ],
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'vaults',
    outputs: [
      { internalType: 'uint256', name: 'totalAssets', type: 'uint256' },
      { internalType: 'uint256', name: 'totalShares', type: 'uint256' },
    ],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'walletConfig',
    outputs: [
      { internalType: 'contract IPermit2', name: 'permit2', type: 'address' },
      { internalType: 'address', name: 'entryPoint', type: 'address' },
      { internalType: 'address', name: 'atomWarden', type: 'address' },
    ],
  },
  { inputs: [], stateMutability: 'payable', type: 'receive' },
]
