export const multivaultAbi = [
  { inputs: [], type: 'error', name: 'MultiVault_AdminOnly' },
  { inputs: [], type: 'error', name: 'MultiVault_ArraysNotSameLength' },
  { inputs: [], type: 'error', name: 'MultiVault_AtomDoesNotExist' },
  {
    inputs: [{ internalType: 'bytes', name: 'atomUri', type: 'bytes' }],
    type: 'error',
    name: 'MultiVault_AtomExists',
  },
  { inputs: [], type: 'error', name: 'MultiVault_AtomUriTooLong' },
  { inputs: [], type: 'error', name: 'MultiVault_BurnFromZeroAddress' },
  { inputs: [], type: 'error', name: 'MultiVault_BurnInsufficientBalance' },
  { inputs: [], type: 'error', name: 'MultiVault_DeployAccountFailed' },
  { inputs: [], type: 'error', name: 'MultiVault_DepositOrWithdrawZeroShares' },
  { inputs: [], type: 'error', name: 'MultiVault_HasCounterStake' },
  { inputs: [], type: 'error', name: 'MultiVault_InsufficientBalance' },
  {
    inputs: [],
    type: 'error',
    name: 'MultiVault_InsufficientDepositAmountToCoverFees',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'remainingShares', type: 'uint256' },
    ],
    type: 'error',
    name: 'MultiVault_InsufficientRemainingSharesInVault',
  },
  { inputs: [], type: 'error', name: 'MultiVault_InsufficientSharesInVault' },
  { inputs: [], type: 'error', name: 'MultiVault_InvalidExitFee' },
  { inputs: [], type: 'error', name: 'MultiVault_InvalidFeeSet' },
  { inputs: [], type: 'error', name: 'MultiVault_MinimumDeposit' },
  { inputs: [], type: 'error', name: 'MultiVault_OperationAlreadyExecuted' },
  { inputs: [], type: 'error', name: 'MultiVault_OperationAlreadyScheduled' },
  { inputs: [], type: 'error', name: 'MultiVault_OperationNotScheduled' },
  { inputs: [], type: 'error', name: 'MultiVault_ReceiveNotAllowed' },
  { inputs: [], type: 'error', name: 'MultiVault_TimelockNotExpired' },
  { inputs: [], type: 'error', name: 'MultiVault_TransferFailed' },
  {
    inputs: [
      { internalType: 'uint256', name: 'subjectId', type: 'uint256' },
      { internalType: 'uint256', name: 'predicateId', type: 'uint256' },
      { internalType: 'uint256', name: 'objectId', type: 'uint256' },
    ],
    type: 'error',
    name: 'MultiVault_TripleExists',
  },
  { inputs: [], type: 'error', name: 'MultiVault_VaultDoesNotExist' },
  { inputs: [], type: 'error', name: 'MultiVault_VaultIsTriple' },
  { inputs: [], type: 'error', name: 'MultiVault_VaultNotAtom' },
  { inputs: [], type: 'error', name: 'MultiVault_VaultNotTriple' },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'creator',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'address',
        name: 'atomWallet',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'bytes',
        name: 'atomData',
        type: 'bytes',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'vaultID',
        type: 'uint256',
        indexed: false,
      },
    ],
    type: 'event',
    name: 'AtomCreated',
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'sender',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'address',
        name: 'receiver',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'uint256',
        name: 'vaultBalance',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'assets',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'shares',
        type: 'uint256',
        indexed: false,
      },
      { internalType: 'uint256', name: 'id', type: 'uint256', indexed: false },
    ],
    type: 'event',
    name: 'Deposited',
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'sender',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'address',
        name: 'protocolVault',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
        indexed: false,
      },
    ],
    type: 'event',
    name: 'FeesTransferred',
    anonymous: false,
  },
  {
    inputs: [
      { internalType: 'uint8', name: 'version', type: 'uint8', indexed: false },
    ],
    type: 'event',
    name: 'Initialized',
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
        indexed: false,
      },
    ],
    type: 'event',
    name: 'Paused',
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'sender',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'address',
        name: 'owner',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'uint256',
        name: 'vaultBalance',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'assets',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'shares',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'exitFee',
        type: 'uint256',
        indexed: false,
      },
      { internalType: 'uint256', name: 'id', type: 'uint256', indexed: false },
    ],
    type: 'event',
    name: 'Redeemed',
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'creator',
        type: 'address',
        indexed: true,
      },
      {
        internalType: 'uint256',
        name: 'subjectId',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'predicateId',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'objectId',
        type: 'uint256',
        indexed: false,
      },
      {
        internalType: 'uint256',
        name: 'vaultID',
        type: 'uint256',
        indexed: false,
      },
    ],
    type: 'event',
    name: 'TripleCreated',
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
        indexed: false,
      },
    ],
    type: 'event',
    name: 'Unpaused',
    anonymous: false,
  },
  { inputs: [], stateMutability: 'payable', type: 'fallback' },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'SET_ADMIN',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'SET_EXIT_FEE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'atomConfig',
    outputs: [
      { internalType: 'uint256', name: 'atomShareLockFee', type: 'uint256' },
      { internalType: 'uint256', name: 'atomCreationFee', type: 'uint256' },
    ],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'atomDepositFractionAmount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'atoms',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
    name: 'atomsByHash',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'bytes[]', name: 'atomUris', type: 'bytes[]' }],
    stateMutability: 'payable',
    type: 'function',
    name: 'batchCreateAtom',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: 'subjectIds', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'predicateIds', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'objectIds', type: 'uint256[]' },
    ],
    stateMutability: 'payable',
    type: 'function',
    name: 'batchCreateTriple',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'operationId', type: 'bytes32' },
      { internalType: 'bytes', name: 'data', type: 'bytes' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'cancelOperation',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'computeAtomWalletAddr',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'convertToAssets',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'convertToShares',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'count',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'bytes', name: 'atomUri', type: 'bytes' }],
    stateMutability: 'payable',
    type: 'function',
    name: 'createAtom',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'subjectId', type: 'uint256' },
      { internalType: 'uint256', name: 'predicateId', type: 'uint256' },
      { internalType: 'uint256', name: 'objectId', type: 'uint256' },
    ],
    stateMutability: 'payable',
    type: 'function',
    name: 'createTriple',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'currentSharePrice',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'atomId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'deployAtomWallet',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
  },
  {
    inputs: [
      { internalType: 'address', name: 'receiver', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'payable',
    type: 'function',
    name: 'depositAtom',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'address', name: 'receiver', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'payable',
    type: 'function',
    name: 'depositTriple',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'entryFeeAmount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'exitFeeAmount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'generalConfig',
    outputs: [
      { internalType: 'address', name: 'admin', type: 'address' },
      { internalType: 'address', name: 'protocolVault', type: 'address' },
      { internalType: 'uint256', name: 'feeDenominator', type: 'uint256' },
      { internalType: 'uint256', name: 'minDeposit', type: 'uint256' },
      { internalType: 'uint256', name: 'minShare', type: 'uint256' },
      { internalType: 'uint256', name: 'atomUriMaxLength', type: 'uint256' },
      { internalType: 'uint256', name: 'decimalPrecision', type: 'uint256' },
      { internalType: 'uint256', name: 'minDelay', type: 'uint256' },
    ],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'getAtomCost',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'pure',
    type: 'function',
    name: 'getCounterIdFromTriple',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'getDepositFees',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'getTripleAtoms',
    outputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'getTripleCost',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'vaultId', type: 'uint256' },
      { internalType: 'address', name: 'user', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'getVaultBalance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      {
        internalType: 'struct IEthMultiVault.GeneralConfig',
        name: '_generalConfig',
        type: 'tuple',
        components: [
          { internalType: 'address', name: 'admin', type: 'address' },
          { internalType: 'address', name: 'protocolVault', type: 'address' },
          { internalType: 'uint256', name: 'feeDenominator', type: 'uint256' },
          { internalType: 'uint256', name: 'minDeposit', type: 'uint256' },
          { internalType: 'uint256', name: 'minShare', type: 'uint256' },
          {
            internalType: 'uint256',
            name: 'atomUriMaxLength',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'decimalPrecision',
            type: 'uint256',
          },
          { internalType: 'uint256', name: 'minDelay', type: 'uint256' },
        ],
      },
      {
        internalType: 'struct IEthMultiVault.AtomConfig',
        name: '_atomConfig',
        type: 'tuple',
        components: [
          {
            internalType: 'uint256',
            name: 'atomShareLockFee',
            type: 'uint256',
          },
          { internalType: 'uint256', name: 'atomCreationFee', type: 'uint256' },
        ],
      },
      {
        internalType: 'struct IEthMultiVault.TripleConfig',
        name: '_tripleConfig',
        type: 'tuple',
        components: [
          {
            internalType: 'uint256',
            name: 'tripleCreationFee',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'atomDepositFractionForTriple',
            type: 'uint256',
          },
        ],
      },
      {
        internalType: 'struct IEthMultiVault.WalletConfig',
        name: '_walletConfig',
        type: 'tuple',
        components: [
          {
            internalType: 'contract IPermit2',
            name: 'permit2',
            type: 'address',
          },
          { internalType: 'address', name: 'entryPoint', type: 'address' },
          { internalType: 'address', name: 'atomWarden', type: 'address' },
          {
            internalType: 'address',
            name: 'atomWalletBeacon',
            type: 'address',
          },
        ],
      },
      {
        internalType: 'struct IEthMultiVault.VaultConfig',
        name: '_vaultConfig',
        type: 'tuple',
        components: [
          { internalType: 'uint256', name: 'entryFee', type: 'uint256' },
          { internalType: 'uint256', name: 'exitFee', type: 'uint256' },
          { internalType: 'uint256', name: 'protocolFee', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'init',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'isTriple',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'isTripleId',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
  },
  {
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'maxRedeem',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'pause',
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'previewDeposit',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'previewRedeem',
    outputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'protocolFeeAmount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'address', name: 'receiver', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'redeemAtom',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'address', name: 'receiver', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'redeemTriple',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'operationId', type: 'bytes32' },
      { internalType: 'bytes', name: 'data', type: 'bytes' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'scheduleOperation',
  },
  {
    inputs: [{ internalType: 'address', name: 'admin', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setAdmin',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'atomCreationFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setAtomCreationFee',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'atomDepositFractionForTriple',
        type: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setAtomDepositFraction',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'atomShareLockFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setAtomShareLockFee',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'atomUriMaxLength', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setAtomUriMaxLength',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'uint256', name: 'entryFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setEntryFee',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'uint256', name: 'exitFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setExitFee',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'minDeposit', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setMinDeposit',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'minShare', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setMinShare',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'uint256', name: 'protocolFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setProtocolFee',
  },
  {
    inputs: [
      { internalType: 'address', name: 'protocolVault', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setProtocolVault',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'tripleCreationFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setTripleCreationFee',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
    name: 'timelocks',
    outputs: [
      { internalType: 'bytes', name: 'data', type: 'bytes' },
      { internalType: 'uint256', name: 'readyTime', type: 'uint256' },
      { internalType: 'bool', name: 'executed', type: 'bool' },
    ],
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'address', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'tripleAtomShares',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'tripleConfig',
    outputs: [
      { internalType: 'uint256', name: 'tripleCreationFee', type: 'uint256' },
      {
        internalType: 'uint256',
        name: 'atomDepositFractionForTriple',
        type: 'uint256',
      },
    ],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'tripleHash',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'subjectId', type: 'uint256' },
      { internalType: 'uint256', name: 'predicateId', type: 'uint256' },
      { internalType: 'uint256', name: 'objectId', type: 'uint256' },
    ],
    stateMutability: 'pure',
    type: 'function',
    name: 'tripleHashFromAtoms',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'triples',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
    name: 'triplesByHash',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'unpause',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'vaultFees',
    outputs: [
      { internalType: 'uint256', name: 'entryFee', type: 'uint256' },
      { internalType: 'uint256', name: 'exitFee', type: 'uint256' },
      { internalType: 'uint256', name: 'protocolFee', type: 'uint256' },
    ],
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    name: 'vaults',
    outputs: [
      { internalType: 'uint256', name: 'totalAssets', type: 'uint256' },
      { internalType: 'uint256', name: 'totalShares', type: 'uint256' },
    ],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'walletConfig',
    outputs: [
      { internalType: 'contract IPermit2', name: 'permit2', type: 'address' },
      { internalType: 'address', name: 'entryPoint', type: 'address' },
      { internalType: 'address', name: 'atomWarden', type: 'address' },
      { internalType: 'address', name: 'atomWalletBeacon', type: 'address' },
    ],
  },
  { inputs: [], stateMutability: 'payable', type: 'receive' },
]
